import { Cormorant_Garamond, Nunito_Sans, Lora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import FooterSection from "@/components/footer";

const clinicSans = Nunito_Sans({
  variable: "--font-clinic-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const clinicDisplay = Cormorant_Garamond({
  variable: "--font-clinic-display",
  subsets: ["latin"],
  display: "swap",
  weight: ["500", "600", "700"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Skinova - Reveal your best skin with thoughtful care and elegant treatments",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`${clinicSans.className} ${clinicDisplay.className} ${lora.className}`} >
        <Navbar />

        <main className='flex grainy-light flex-col bg-background min-h-screen'>
          <div className='flex-1 flex flex-col h-full'>
            {children}
          </div>
          <FooterSection />
        </main>
      </body>
    </html>
  );
}
